from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.cell(0, 15, 'Project SECURE 3FA', 0, 1, 'C')
        self.set_font('Arial', 'I', 12)
        self.cell(0, 10, 'Architecture, Components & Workflow Overview', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 16)
        self.set_text_color(0, 102, 204)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)
        self.set_text_color(0, 0, 0)

    def chapter_body(self, body):
        self.set_font('Arial', '', 12)
        self.multi_cell(0, 6, body)
        self.ln(5)

    def bullet_point(self, title, description):
        self.set_font('Arial', 'B', 12)
        self.cell(10, 6, '-', 0, 0, 'R')
        self.cell(50, 6, title + ':', 0, 0, 'L')
        
        self.set_font('Arial', '', 12)
        self.multi_cell(0, 6, description)
        self.ln(2)

pdf = PDF()
pdf.add_page()

# Section 1
pdf.chapter_title('1. Technology Stack & What We Use')
pdf.bullet_point('Backend Framework', 'Python with Flask for robust, lightweight server-side routing and API endpoints.')
pdf.bullet_point('Database', 'SQLite3 for structured, file-based data storage of user profiles and authentication secrets.')
pdf.bullet_point('Frontend UI/UX', 'HTML5, Vanilla CSS3, JavaScript. Designed with a Zero Trust, Cyber-Security aesthetic featuring Glassmorphism, neon accents, and smooth transitions.')
pdf.bullet_point('Authentication (JWT)', 'PyJWT for secure session management without server-side state.')
pdf.bullet_point('Cryptography', 'hashlib (SHA-256) for secure, salted password hashing.')
pdf.bullet_point('Biometrics (Face) & Camera', 'OpenCV (cv2) for image processing, dlib and face_recognition libraries for extracting and verifying 128-point facial measurements. Frontend webcam access is handled natively via the HTML5 MediaDevices API.')
pdf.bullet_point('Time-Based OTP', 'PyOTP for generating and validating Google Authenticator synchronized tokens.')

pdf.ln(5)

# Section 2
pdf.chapter_title('2. Python Backend Files')
pdf.bullet_point('app.py', 'The main entry point for the Flask server. Manages all web routes (HTML rendering) and API endpoints (login/registration mechanics). Protects routes using a custom JWT decorator.')
pdf.bullet_point('database.py', 'Handles all interactions with the SQLite database. Creates tables, manages user records, rate limits, stores TOTP secrets, and serializes facial encodings.')
pdf.bullet_point('auth_logic.py', 'Centralizes core authentication mathematics. Responsible for creating password hashes, verifying passwords, and issuing/verifying JSON Web Tokens.')
pdf.bullet_point('face_utils.py', 'Manages computer vision operations. Decodes base64 webcam images, extracts neural face encodings, and compares them during login step 3.')
pdf.bullet_point('totp_utils.py', 'Integrates with PyOTP to generate secret keys, construct QR Code URIs, and validate 6-digit tokens for factor 2.')

pdf.ln(5)

# Section 3
pdf.chapter_title('3. HTML & Frontend Files')
pdf.bullet_point('base.html', 'The foundational layout template. Contains global CSS (animations, cyber-security theme, glassmorphism), the top navigation bar, and the sliding "About 3FA" drawer.')
pdf.bullet_point('home.html', 'The landing page. Features a hero section and explains the Zero Trust Architecture grid to unauthenticated users.')
pdf.bullet_point('register.html', 'The onboarding portal. Collects user profiles (Name, Email, Location), initiates the webcam for facial enrollment, and displays the QR code for Authenticator app setup.')
pdf.bullet_point('login.html', 'A dynamic, 3-step authentication interface. Verifies Password -> Verifies TOTP -> Activates Webcam for Facial Recognition. Uses JavaScript for smooth transitions without reloading.')
pdf.bullet_point('dashboard.html', 'The protected user portal. Displays session stats, user profile context, a visual Authentication Workflow, and a simulated Security Events log.')
pdf.bullet_point('about.html', 'A dedicated informational page breaking down the three factors (Knowledge, Possession, Inherence) and the tech stack.')

pdf.ln(5)

# Section 4
pdf.chapter_title('4. Authentication Workflow Summary')
workflow = (
    "The system enforces a strict 'Zero Trust' pipeline. Users must successfully pass all three factors sequentially:\n\n"
    "Step 1 (Knowledge): The user provides their username and password. The system checks this against salted hashes in the database.\n"
    "Step 2 (Possession): The user inputs a 6-digit token generated by their mobile device (Google Authenticator). The server validates it against the shared secret.\n"
    "Step 3 (Inherence): The webcam captures the user's face. The neural network ensures the physical face perfectly matches the mathematical encoding saved during registration.\n\n"
    "Only after all three factors pass does the server issue a JWT, granting access to the Dashboard."
)
pdf.chapter_body(workflow)

output_path = os.path.join(os.getcwd(), 'Project_SECURE_3FA_Documentation.pdf')
pdf.output(output_path)
print(f"PDF successfully generated at: {output_path}")
